### ISSUE TITLE
Copy change for initialize/finalize script labels

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-PAT#105]
instead of "Server Initialization|Finalization": "Analysis Initialization|Finalization"
instead of "Worker Initialization|Finalization": "Datapoint Initialiazation|Finalization"

The current naming is misleading regarding when the scripts run.  Worker scripts, for example, run 1x each per datapoint rather that once per worker.  

@kflemin @nllong @rHorsey @DavidGoldwasser FYI & let me know if you think this will cause confusion.

**Comment by shorowit** [comment]
Just got confused by the names in PAT again today.

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio-PAT/pull/131
