### ISSUE TITLE
PAT reports not finding data

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#106]
Justing 2.72 in project with current OpenStudio Measure report. For some reason some registerValues are not being found even though they are in the json (and OSW) file for the datapionts. I can't dig into cause right now, but wanted to document. On the same project "End Use Comparison" report is blank

![screen shot 2019-01-25 at 12 32 50 pm](https://user-images.githubusercontent.com/4857055/51768414-7b2cd200-209d-11e9-94b4-f5e7ce4b90e0.png)

I suppose any of the three of us could fix this if we had time. I have also seen some non-repeatable stability issues on larger projects. For reference, this is the issue in screenshot is Maalka EE project.

**Comment by kflemin** [comment]
Confirmed that this was not a PAT bug.  Just a misconfiguration in the project output variables.
