### ISSUE TITLE
Create standalone installer for develop3

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-PAT#109]

**Comment by macumber** [comment]
Basic task is to remove the PAT directory from develop3, move all of the CMake code to build the package to the OpenStudio-PAT repository

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/pat/CMakeLists.txt#L3

**Comment by macumber** [comment]
Currently OpenStudio refers to a SHA in OpenStudio-PAT.  We need to reverse this.  In future, OpenStudio-PAT will refer to a build of OpenStudio, It will have to suck in the OS CLI, Ruby, etc that it needs in its package.

**Comment by tijcolem** [comment]
This is done. Was part of the OpenStudio 3.0.0 milestone release. https://github.com/NREL/OpenStudio-PAT/releases/tag/v3.0.0
