### ISSUE TITLE
Additional metrics for algorithmic calibration sample projects

### ISSUE THREAD

**Issue by antoine-galataud** [NREL/OpenStudio-PAT#114]
Hi,

I'm currently working on a building model calibration project and I'd like to use SEB sample project as a baseline: I'd reuse same seed model, measures and calibration data and compare results with the one obtained using PAT. 
Apart from CSVs that can be found in sample_projects dir, is there any other place I could find training metrics? I'm particularly interested in training times, speed of convergence (where applicable), sampling rate, and AWS resources utilization.

Thanks!

**Comment by brianlball** [comment]
This question should be posted in a forum like https://unmethours.com/questions/

**Comment by antoine-galataud** [comment]
done here: https://unmethours.com/question/40003/pat-2-sample-calibration-projects-metrics-and-results/
