### ISSUE TITLE
warn users about server node CPU requirements

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-PAT#118]
related: https://github.com/NREL/OpenStudio-aws-gem/issues/29

We should warn the user or expose the swarm reservation calculation to the user so that the user doesnt choose an incompatible configuration.

10 c3.8xlarge (32 core) worker example:
Total_procs = 320 (32 * 10)
mongo_cores = (total_procs / 64.0).ceil  = 5
web_cores = (total_procs / 32.0).ceil  = 10
rserve = 1
web_background = 1
queue = 1

**Comment by tijcolem** [comment]
Consider moving this tohttps://github.com/NREL/OpenStudio-server-helm.  Include calcs for cluster size.

**Comment by tijcolem** [comment]
We can expand on this in new k8s/helm at https://github.com/NREL/openstudio-server-helm/
