### ISSUE TITLE
Clean up OpenStudio-PAT repo README

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#12]
_From @asparke2 on March 3, 2017 16:15_

requested by @pmkary

_Copied from original issue: NREL/OpenStudio#2498_

**Comment by kflemin** [comment]
_From @asparke2 on March 3, 2017 16:17_

Agree.  At a minimum, we should include:

1. What the repo is
2. Where to report issues (OpenStudio issues)
3. Where the build instructions live (Wiki)

**Comment by kflemin** [comment]
_From @macumber on March 6, 2017 17:11_

@asparke2 do you really want this assigned to you?  should be assigned to @evanweaver or @kflemin ?

**Comment by kflemin** [comment]
_From @macumber on June 28, 2017 15:53_

@asparke2 is this complete?  can we close it?

**Comment by kflemin** [comment]
_From @asparke2 on June 28, 2017 16:30_

No, it is still the electron boilerplate:

https://github.com/NREL/openstudio-pat

**Comment by kflemin** [comment]
Done!  @asparke2, can we close?

**Comment by pouyakary** [comment]
I guess so
