### ISSUE TITLE
Upload Linux dependencies to S3

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-PAT#145]
cf https://github.com/NREL/OpenStudio-PAT/pull/94#issuecomment-627016149

> Basically I think we need to update dependencies to s3.
> I can provide the linux server + ruby 2.5.5. On top of that needs the EnergyPlus one, the OpenStudio 3.0.0 one (the tar.gz on NREL/OpenStudio is a bit broken, path includes "/usr/local/openstudio-3.0.0" should be "OpenStudio" to work here, and bin/openstudio symlink need to be added), and the mongodb one. Then we can take it from here with people more knowledgeable about how PAT works.

Then update the manifest.json accordingly.

**Comment by tijcolem** [comment]
@jmarrec Do you have links to your linux server and ruby 2.5.5 builds? I will add these to s3.

**Comment by tijcolem** [comment]
This is now done. Ref de4cbb3aa346920c1fe2d1ea7848c19a4f795c34
