### ISSUE TITLE
Error with Energyplus Economic measure.

### ISSUE THREAD

**Issue by rwadhwa910** [NREL/OpenStudio-PAT#149]
While running a PAT analysis, I used an Energyplus measure (ExcelDAT Tariff Selection),  I got an error (Lifecycle cost User Price escalation Fueloil#1 and Fueloil#2Failed to match against Enum values). The same issue also came when I used the tariff file for Austin Energy Tariff selection. I was able to resolve it by changing the Fueloil#1 to 
![PAT Error](https://user-images.githubusercontent.com/63880759/84536816-dae44700-acab-11ea-9b74-60943b47c97e.PNG)
FueloilNo1 in measure.rb file of the measure.

**Comment by DavidGoldwasser** [comment]
Closing this, is issue with Tariff measures, not with PAT
