### ISSUE TITLE
Measure Update doesn't function for some measures on some Windows machines

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#154]
This is tested with PAT 3.0.  on both mac and windows and it works for me, but I watched @rwadhwa910 use it and he couldn't see the updates. We are using same PAT project (clean checkout from repo) and have the same my measures directory  (also clean checkout from repository). Not sure of the cause but here is screenshot of what is should look like when using AEDG repository for my measures.

![aedg_update_office](https://user-images.githubusercontent.com/4857055/85634357-707ebf80-b638-11ea-8f6b-69dbc15374c8.png)

**Comment by rwadhwa910** [comment]
This is the issue that I was having with my machine.

After updating the measures on the local repository, I cannot see the update icon on my Windows laptop in PAT application. Although the same measures when opened in MAC PAT application shows update icon. I have attached the screenshot for the PC.
![85635168-7b3a5400-b63a-11ea-95c9-dcf2a493e4cf](https://user-images.githubusercontent.com/63880759/85780591-06225980-b6e2-11ea-98f4-65d217aaf85f.png)

**Comment by DavidGoldwasser** [comment]
@rwadhwa910 You screenshot shows K12 PAT project. Those measures were already updated on the GitHub branch you were using. can you put screenshot up of the same PAT project as my screenshot `pat_sddc_office`. I think that is what you showed be on Teams yesterday.

**Comment by rwadhwa910** [comment]
@DavidGoldwasser  I can see the update icon now on my machine.

**Comment by DavidGoldwasser** [comment]
Going to close this for now but will re-open if we can confirm this happening elsewhere. I'm aware of one other report, but it involved a measure that was copied without giving it a new UUID.
