### ISSUE TITLE
PAT wont run. Server connection issue? 

### ISSUE THREAD

**Issue by kmark86** [NREL/OpenStudio-PAT#169]
I'm trying to run the simulations on PAT. However,  I keep getting a server error. I've tried using the Server Troubleshooting Tools to Start and Ping, but nothing has worked. How can I resolve this? Thanks!
![PAT ERROR](https://user-images.githubusercontent.com/73257505/96788089-def24500-13c0-11eb-8e5f-29b3b696b51b.JPG)

**Comment by tijcolem** [comment]
Hi, It looks like you are windows from looking at the paths. Do you have another PAT version installed and/or running? Only one version can be running.  Are there are any logs in your PAT workspace directory?  Should be this: 

`C:\Users\kmark\Documents\Test\MidRise PAT(3)\logs `

If you running from a previous PAT project and the PAT application does not shut down gracefully, the mongo lock file may persist in the `data` dir this workspace and this could be the reason it's not starting. The logs folder in your would tell us more info.  

You can also try running the startup server command via the command line. Just copy the entire startup command and run it. For example, this is how I can start it up on my machine (the PAT workspace will need to be changed). 

`"C:\ParametricAnalysisTool-3.1.0\pat\ruby\bin\ruby.exe" "C:\ParametricAnalysisTool-3.1.0\pat\OpenStudio-server\bin\openstudio_meta" start_local --worker-number=3 --energyplus-exe-path="C:\ParametricAnalysisTool-3.1.0\pat\EnergyPlus\energyplus.exe" --openstudio-exe-path="C:\ParametricAnalysisTool-3.1.0\pat\OpenStudio\bin\openstudio.exe" --ruby-lib-path="C:\ParametricAnalysisTool-3.1.0\pat\OpenStudio\Ruby" --mongo-dir="C:\ParametricAnalysisTool-3.1.0\pat\mongo\bin" --debug "C:\Users\Tim\git\OpenStudio-PAT\sample_projects\Office_HVAC"`

Many times if you simply remove the "data" directory in the PAT project this will clear up any of the mongo lock file. Be careful and make a backup though as you don't want to lose any of your existing work.

**Comment by brianlball** [comment]
any updates on this @kmark86 ?

**Comment by macabilo2** [comment]
I have a similar situation where I cannot start the PAT local server. I tried the suggestion by @tijcolem and executed the command via CL. After waiting for a while, it prompts that Rails failed to launch.

In the rails.log, this is shown:
`D:\Program Files\ParametricAnalysisTool-3.4.0\pat\ruby\bin\ruby.exe: invalid switch in RUBYOPT: -F (RuntimeError)`

I attached both the mongo and rails log files so you can check. I am new to PAT and this would be my first analysis. I just cannot seem to start the local server.

[mongo.log](https://github.com/NREL/OpenStudio-PAT/files/9016418/mongo.log)
[rails.log](https://github.com/NREL/OpenStudio-PAT/files/9016419/rails.log)

**Comment by macabilo2** [comment]
Furthermore, here is a verbose output of the same command:

[test_start.log](https://github.com/NREL/OpenStudio-PAT/files/9016465/test_start.log)

**Comment by brianlball** [comment]
@planetwsn try installing PAT in a directory without any spaces in the path name.  I think the "Program Files" is causing a problem.

**Comment by macabilo2** [comment]
@brianlball  Thanks a lot! It worked like a charm.

**Comment by brianlball** [comment]
@planetwsn, glad it worked. also check out unmethours.com, its a good resource for BEM related issues.
