### ISSUE TITLE
Escape out of viewing Reporting Measure

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio-PAT#171]
When viewing Reporting Measures from the Run tab it would be nice to be able to use `Esc` to close window rather than having to click `Ok`, which is the behavior that other tabs have (e.g. when adding measures).

**Comment by kflemin** [comment]
@MatthewSteen cannot reproduce...pressing the ESC key closes the report window for me.

**Comment by MatthewSteen** [comment]
Fixed in 3.2.0.
