### ISSUE TITLE
cancel run if user terminates server while running analysis in algorithmic mode

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio-PAT#174]
User's can get trapped on the Run tab with the following steps. This was with 3.1.0 on Ubuntu.
1. Start cloud server
2. Start running an analysis
3. Terminate the cloud server
4. Try to navigate to another tab

![image](https://user-images.githubusercontent.com/8397034/101674577-e7a4e600-3a15-11eb-901e-4f7516f64c1e.png)

Workaround...
1. Re-Start cloud server
2. Wait
3. `Run Entire Workflow`
4. Wait
5. `Cancel Analysis`

**Comment by kflemin** [comment]
this will no longer be an issue with the cloud options removed in the next release
