### ISSUE TITLE
PAT runs forever

### ISSUE THREAD

**Issue by h9a2n3d5** [NREL/OpenStudio-PAT#180]
Hi!

I'm trying to use PAT application for an internship project but I just cant make it work. When I run an analysis, PAT stays on "Analysis started" and keeps on running forever.
I've read about the print issues ($ etc...) so I just made a test version as simple as possible with the OSM file of my project (library of 2 stories), a weather file, 1 measure, 1 option and 1 alternative. I also placed all my files on my desktop so the path is the shortest possible.
I'm a bit new with PAT so maybe I'm missing something very basic but I've been trying for several days and I just cant succeed.

Thanks for your help!

**Comment by brianlball** [comment]
Try running the sample projects here https://github.com/NREL/OpenStudio-PAT/tree/develop/sample_projects

This is also a good resource with examples  https://www.dbooks.org/building-energy-modeling-with-openstudio-3319778099/

**Comment by h9a2n3d5** [comment]
I tried with one of the sample you linked me : Office_Study (seed & weather), and with 1 option ("Increase R-value of Insulation for Roofs to a Specific Value") and 1 alternative.

It still doesnt work and runs forever with "Analysis started".

Should I try to uninstall and reinstall PAT ?

**Comment by h9a2n3d5** [comment]
I dont know if it has to do with it but usually the local server doesnt work when I launch the application. I have to "Start local server" and then "Ping server and set status" so the server is started and the server status is ok.

**Comment by brianlball** [comment]
the local server is off my default.  you have to manually start it.

**Comment by brianlball** [comment]
what version are you running?  what operating system?

**Comment by h9a2n3d5** [comment]
PAT 3.1.0
Windows 10 x64

**Comment by brianlball** [comment]
if you open the developers console windows from one of the top drop downs, you should see the commands PAT is running when it starts the server and any error messages.  you can get more info by copying the commands and running them from a terminal or power shell.

**Comment by h9a2n3d5** [comment]
I did this and when the analysis is started, those 3 lines are written over and over :
"update datapoints succeeded
Updated Datapoints with Reports
datapoints after download"

So is it supposed to be good and it's just my laptop which is very slow ?

I have some errors before I start the analysis but they are all linked to the server status which is on and ok afterwards.
And I also have 2 warnings : 
1st is "No default AMI found for package OS version 3.1"
2nd is "Deprecation" of some resources

**Comment by brianlball** [comment]
can you post the developer console log here?  an example of what that looks like is here
![image](https://user-images.githubusercontent.com/2235296/116279098-62139f80-a744-11eb-8c0f-e4cac9771bf6.png)

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/116293192-9bf49e00-a764-11eb-9b6d-d28d522a6f15.png)

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/116293345-c7778880-a764-11eb-8173-f15d48f3acb1.png)

**Comment by brianlball** [comment]
1. can you try running this command in a power shell terminal and post the results (assuming a server has started):

C:\ParametricAnalysisTool-3.1.0\pat\ruby\bin\ruby.exe C:\ParametricAnalysisTool-3.1.0\pat\OpenStudio-server\bin\openstudio_meta run_analysis --debug --verbose "C:\Users\andre\Desktop\testPAT\testPAT.json" 'http://localhost:8080'

2. try moving the testPAT files to a folder like c:\projects.
3.  open 'localhost:8080' in a web browser.  do you see the analysis running or results info anywhere?

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/116491118-1dccf000-a867-11eb-8411-21ac0edfb849.png)

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/116491536-18bc7080-a868-11eb-9756-22c8302a99c4.png)
![image](https://user-images.githubusercontent.com/83079007/116491586-38ec2f80-a868-11eb-8b77-2af818722527.png)

**Comment by h9a2n3d5** [comment]
I moved testPAT to c:\ and it's just doing the same thing
This is what I get on the server

**Comment by brianlball** [comment]
the powershell windows says it cant find the .json file, which is the project description.  make sure that file and the .zip file exist and those paths are correct.  Also try to use the example projects from the PAT directory.  those are known to work.

**Comment by h9a2n3d5** [comment]
I tried the Office study sample project and it still doesn't work
This is what I get
![image](https://user-images.githubusercontent.com/83079007/116715828-127fde80-a9a5-11eb-85db-7cc0e4b95578.png)
![image](https://user-images.githubusercontent.com/83079007/116715864-1b70b000-a9a5-11eb-9a9b-896b9c741c70.png)
![image](https://user-images.githubusercontent.com/83079007/116715904-262b4500-a9a5-11eb-9fde-8a64d15b5c1b.png)

**Comment by h9a2n3d5** [comment]
And this is the folder of my test project testPAT
![image](https://user-images.githubusercontent.com/83079007/116716496-d1d49500-a9a5-11eb-9c55-6423ec4f564e.png)

**Comment by brianlball** [comment]
can you post the full console log.
also, on the analysis page, the can you click the log button (in between JSON and Snow Cluster) and post that log.

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/116896597-689d8d80-ac02-11eb-94e1-e44f03cf9dba.png)
![image](https://user-images.githubusercontent.com/83079007/116896628-718e5f00-ac02-11eb-9c66-d93b32def003.png)
![image](https://user-images.githubusercontent.com/83079007/116896668-79e69a00-ac02-11eb-834f-706aceda4aa2.png)
![image](https://user-images.githubusercontent.com/83079007/116896701-81a63e80-ac02-11eb-9210-f522ef22f1eb.png)

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/116896760-8e2a9700-ac02-11eb-9796-339470095a85.png)

**Comment by brianlball** [comment]
okay there we go.  looks like there are errors exporting the OSA and its coming from blank or "" values for arguments.   look back at the red messages and try to correct the ones that say "this will most likely cause errors on Server".  those arguments need some kind of default value.

**Comment by h9a2n3d5** [comment]
Yes I did that. That's why there are 5 errors at first, then still 1 because I missed it, and finally the analysis with supposedly no mistakes starts right after with "(16) ["Secondary School", ..."

**Comment by brianlball** [comment]
okay, so are there datapoints being created in the server GUI (localhost:8080)?

**Comment by h9a2n3d5** [comment]
No...
![image](https://user-images.githubusercontent.com/83079007/116906554-6a6d4e00-ac0e-11eb-830a-ccb831665b67.png)

**Comment by h9a2n3d5** [comment]
When I click on "Analysis Data" in "Data and Visualizations" in the server, I got this. Is it normal ?
![image](https://user-images.githubusercontent.com/83079007/116906765-a99b9f00-ac0e-11eb-8d6d-474c31a291fb.png)

**Comment by brianlball** [comment]
okay, i think the analysis you are running requires Algorithmic mode, which is not avail on a local server.  Try running the Office HVAC project.  that should be a manual run and not algorithmic.

if you want to run algorithmic, you'll need to use the cloud providers (AWS, etc)

**Comment by h9a2n3d5** [comment]
You were right but it still doesn't work
![image](https://user-images.githubusercontent.com/83079007/116917793-1d44a880-ac1d-11eb-9624-94f9ef5bc3e2.png)
![image](https://user-images.githubusercontent.com/83079007/116917810-233a8980-ac1d-11eb-8372-7321aa188f23.png)
![image](https://user-images.githubusercontent.com/83079007/116917838-2df51e80-ac1d-11eb-83f1-6847c241076b.png)
![image](https://user-images.githubusercontent.com/83079007/116917877-3a797700-ac1d-11eb-8498-7a96d146087d.png)
![image](https://user-images.githubusercontent.com/83079007/116917898-3fd6c180-ac1d-11eb-89fe-f76dc6289972.png)
![image](https://user-images.githubusercontent.com/83079007/116917920-45340c00-ac1d-11eb-99eb-ff4704fea440.png)
![image](https://user-images.githubusercontent.com/83079007/116917943-4c5b1a00-ac1d-11eb-9fb4-23af40304f8e.png)

**Comment by brianlball** [comment]
hmm, the run analysis response undefined is concerning.
try to stop the server and restart.
then run the "run analysis" command in a power shell window and add the --verbose --debug options like before.

**Comment by brianlball** [comment]
similiar to what Tim posted in this issue https://github.com/NREL/OpenStudio-PAT/issues/169

**Comment by h9a2n3d5** [comment]
Here is the result of the command 
![image](https://user-images.githubusercontent.com/83079007/117026337-b29d7680-acc9-11eb-8bba-b6946a2c04ca.png)
![image](https://user-images.githubusercontent.com/83079007/117026392-c052fc00-acc9-11eb-9e42-2b927dc7bbc1.png)

**Comment by h9a2n3d5** [comment]
I'm going to check on the on the issue you suggested

**Comment by h9a2n3d5** [comment]
On the other issue, tijcolem is talking about the logs file and this is what I got in mine
![image](https://user-images.githubusercontent.com/83079007/117028260-884cb880-accb-11eb-852a-8787fad1cc43.png)

I also checked in the data file and there's just a db empty file before I launch PAT

**Comment by brianlball** [comment]
your CLI message look good. everything gets created.  do you see anything in the log files?

**Comment by h9a2n3d5** [comment]
which log file should I check ?

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/117033232-2a6e9f80-acd0-11eb-8b0b-f601a4a4b4a3.png)
![image](https://user-images.githubusercontent.com/83079007/117033260-335f7100-acd0-11eb-9a8d-5053fd028c8c.png)
![image](https://user-images.githubusercontent.com/83079007/117033296-3c504280-acd0-11eb-9f01-a0bcb0cb3aec.png)
![image](https://user-images.githubusercontent.com/83079007/117033333-42deba00-acd0-11eb-8016-f9bbfbd561e4.png)

**Comment by h9a2n3d5** [comment]
![image](https://user-images.githubusercontent.com/83079007/117033447-5db12e80-acd0-11eb-9c94-699bdbcb2130.png)

**Comment by brianlball** [comment]
I chatted with Tim and the consensus is that your hostname (which comes from PC name) is causing problems because of the umlaut.  "failed to obtain address information for hostname" in the above graphic.  Can you try to rename your PC to something like 'andre' and see if that helps?   

https://www.cnet.com/how-to/how-to-change-your-computers-name-in-windows-10/

**Comment by h9a2n3d5** [comment]
It actually worked... the analysis started ! I thought it was ok because my file name was "andre" but I havent thought about my computer name .. this is so frustrating ahah. Thanks for your help and time !

But now every time a datapoint is created I get this error :
![image](https://user-images.githubusercontent.com/83079007/117046804-1f6f3b80-acdf-11eb-9daa-7418cd5f54a7.png)

**Comment by h9a2n3d5** [comment]
It does say on the localhost that the analysis is completed normal

**Comment by brianlball** [comment]
yeah, we've never seen this type of error before.
Are you getting results now?

**Comment by h9a2n3d5** [comment]
Yes I get my OpenStudio results

**Comment by tijcolem** [comment]
Just chiming in here. Glad you got it working.  Those last errors your showing are actually common.  The PAT client queries rails server to see if the data point is finished, and it doesn't exist yet, it throws a 422/404 error, which in this purpose just means the run hasn't finished yet and it'll collect the response on the next try.

**Comment by h9a2n3d5** [comment]
Ok thanks for the precision !
Big thank you for your help
