### ISSUE TITLE
Some measures do not work in the PAT tool

### ISSUE THREAD

**Issue by LouYingli** [NREL/OpenStudio-PAT#184]
Issue overview
--------------
Some measures work well in the OpenStudio Application, but do not work in the PAT, for example, SetBoilerThermalEfficiency, and SetWaterHeaterEfficiencyHeatLossandPeakWaterFlowRate. 

## Current Behavior
There is an error reminding in the PAT tool: !!!!*** This Measure is not Applicable to loaded Model. Read the description and choose an appropriate baseline model. ***!!!!

## Expected Behavior
There should not have the error reminding in the PAT.

## Steps to Reproduce
1.	Add OpenStudio Measures named “SetWaterHeaterEfficiencyHeatLossandPeakWaterFlowRate” from Building Component Library.
2.	Click OK.
Following is the video link of this bug.
https://drive.google.com/file/d/1s-1WlPm-UV8171ZCZGJ2KVa65DanBtID/view?usp=sharing

### Environment
 - Platform (Operating system, version): Windows 10 Pro (1909) for Workstations
 - Version of PAT: ParametricAnalysisTool-3.1.0

**Comment by kflemin** [comment]
@LouYingli, this is not a PAT issue, but an issue with the measures themselves.  I am not sure why they have that strange argument, but you can try to contact the PNNL group who made these measures.  Or you can try to modify them yourself and include them in your local 'MyMeasures' directory.
