### ISSUE TITLE
[Enhancement] Bump node from v8 to v18 LTS (and therefore bump packages too)

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-PAT#197]
https://github.com/NREL/OpenStudio-PAT/blob/ee3c6c44156d9409d876f12115e681022cafb21b/package.json#L71-L73

Node v16 is the current LTS version.

Node.js 8 was initially released on 2017-05-30, and its End-of-Life was 31st December 2019, so it's been EOL since more than 2 years.

**Sub Task Issues**
- [x] #211
- [x] #212
- [x] #213
- [x] #214
- [x] #215
- [x] #216
- [x] #217
- [x] #221

**Comment by tijcolem** [comment]
@bstein We can keep this as the top level ticket. Please open new GitHub sub task issues related to this update.
