### ISSUE TITLE
PAT version unknown on mac

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#200]
This is related to a prior fixed issue #20. In the application, the `About` menu knows shows the correct version, but if I have multiple PAT apps on my computer (which I often do) the version that shows there shows as `Unknown version`. This is of very low importance, but if there is a way for the version to make it through there, it would be nice. My work around is to either use the date to identify the version, or launch from finder, instead of search results.

<img width="1101" alt="pat_version" src="https://user-images.githubusercontent.com/4857055/154529451-4c436246-9eb2-4f9e-9a51-fba426e52415.png">

**Comment by wenyikuang** [comment]
<img width="527" alt="image" src="https://github.com/NREL/OpenStudio-PAT/assets/137332549/b46f59a6-b7a3-44e1-a2ed-1c00f2c6f179">

I can confirmed it fixed.
