### ISSUE TITLE
PAT fails as soon as the analysis starts

### ISSUE THREAD

**Issue by ruggieroguida** [NREL/OpenStudio-PAT#209]
```
Version: PAT 3.4.0 (Installed from the binaries in the release section)
OS: MacOS Monterey 12.4 (apple silicon)
```
I receive this error when trying to run a simple analysis in PAT with the meausure `Increase R-value of Insulation for Exterior Walls By a Specified Percentage`. It seems that the simulations do not even start.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/8143193/174475406-aff7c0b6-468a-479c-8b6d-98efab24ebc3.png">

The measure works if applied directly to the seed model. The output from the Developers Tools is the following

<img width="886" alt="image" src="https://user-images.githubusercontent.com/8143193/174475450-4d6104a4-def5-410b-9ee1-2bcac99f5563.png">

I am also attaching the analysis json file and the project

[TestPAT01.json.zip](https://github.com/NREL/OpenStudio-PAT/files/8935094/TestPAT01.json.zip)

[TestPAT01.zip](https://github.com/NREL/OpenStudio-PAT/files/8935101/TestPAT01.zip)

[delayed_job.log](https://github.com/NREL/OpenStudio-PAT/files/8935147/delayed_job.log)

**Comment by ruggieroguida** [comment]
Just in case someone has the same problem. It seems that the library `libintl.8.dylib` was missing from the PAT application in `/Applications/ParametricAnalysisTool-3.4.0/ParametricAnalysisTool.app/Contents/Resources/openstudio/EnergyPlus/`.

I copied it from the main E+ folder with 

`cp /Applications/EnergyPlus-22-1-0/libintl.8.dylib /Applications/ParametricAnalysisTool-3.4.0/ParametricAnalysisTool.app/Contents/Resources/openstudio/EnergyPlus/`

and it worked.

**Comment by tijcolem** [comment]
@ruggieroguida Thanks for reporting this and posting the workaround. I updated the 3.4.0 PAT release installer for MacOS to fix this.
