### ISSUE TITLE
Fix Outputs page grid

### ISSUE THREAD

**Issue by bstein** [NREL/OpenStudio-PAT#231]
After upgrading [angular-ui-grid](https://www.npmjs.com/package/angular-ui-grid) in issue #225 with PR #228, the table does not appear correctly on the Outputs page when the analysis mode is set to "Algorithmic", as shown in this screenshot:

![broken-ui-grid](https://user-images.githubusercontent.com/6434784/194109473-f847429c-0fb9-4162-9dfa-3b86678df303.png)

The reason for this is that the styling in the [headerTemplate.html](https://github.com/NREL/OpenStudio-PAT/blob/develop/app/app/outputs/headerTemplate.html) file is not compatible with `angular-ui-grid` v4.6.3 and later. This file needs to be updated to be compatible with the latest version.

**Comment by tijcolem** [comment]
@bstein Good catch!
