### ISSUE TITLE
cpack error when generating Windows installer

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio-PAT#235]
@bstein Looks like this is still an issue when generating windows packages. Maybe it was when the CI runner was upgraded from 2019 to 2022?  Take a look at this line here: https://github.com/NREL/OpenStudio-PAT/actions/runs/3340691973/jobs/5531082030#step:6:160. It's annoying this doesn't throw an error in the build. Maybe I can add a second step to verify the contents after. 

I think this was related:  https://github.com/NREL/OpenStudio-PAT/issues/221

**Comment by tijcolem** [comment]
2022 did work. This was a working build looking back in the history.  https://github.com/NREL/OpenStudio-PAT/actions/runs/2862855047/jobs/4539303058

**Comment by tijcolem** [comment]
More digging. 

Last good windows cpack build:  
https://github.com/NREL/OpenStudio-PAT/actions/runs/2905293794/jobs/4624071734
Commit: https://github.com/NREL/OpenStudio-PAT/commit/89155fca13601fe40ab1f4226d34b433f4cb5653

I think this may have broke it
https://github.com/NREL/OpenStudio-PAT/actions/runs/2949170660/jobs/4712386755
Commit: https://github.com/NREL/OpenStudio-PAT/commit/7942b2391d0f82f8dbefba05e07d4c2682ffb9c5

**Comment by tijcolem** [comment]
A little more info. This commit here   https://github.com/NREL/OpenStudio-PAT/commit/70bce19ec128d2b7b37518ccc1652c7f5af61a7f built fine on Aug 19 in 35m 15s. I replayed this exact same commit just now using the same workflow and it failed.  Smells like a version change caused something to break. 

Succeeded ( Aug 19 in 35m 15s):  https://github.com/NREL/OpenStudio-PAT/actions/runs/2891652196/jobs/4598886496

Failed ( Oct 27  in 41m 45s) https://github.com/tijcolem/OpenStudio-PAT/actions/runs/3342398966/jobs/5534583265
Succeed:

**Comment by bstein** [comment]
@tijcolem I created the branch [`fix-cpack-error-windows`](https://github.com/NREL/OpenStudio-PAT/tree/fix-cpack-error-windows) to work on this

**Comment by tijcolem** [comment]
Thanks @bstein for looking into this!

**Comment by bstein** [comment]
@tijcolem Of course! Fortunately, this was a straightforward issue where Windows wouldn't run the `./node_modules/.bin/gulp` executable. The workaround is to use `npx gulp` instead, which is functionally the same.

I have opened a PR for the fix: #236
