### ISSUE TITLE
PAT start local server error

### ISSUE THREAD

**Issue by nixub-a** [NREL/OpenStudio-PAT#253]
I am struggling to get my Windows 10 PC to start the local server in PAT. On the contrary, my weak Windows 11 laptop has no errors. I am using PAT v3.2.1. My case is identical to issue #169 (https://github.com/NREL/OpenStudio-PAT/issues/169). None of the troubleshooting steps fixed my problem. I already tried v3.5.1 and encountered the same issue. I think the problem is my PC. 

![image](https://user-images.githubusercontent.com/124007548/227755902-0c9ea95f-65e1-48dd-81a6-c11709d75e15.png)

I kindly ask for any suggestions. Thanks.

**Comment by brianlball** [comment]
copy the start server command to a terminal and add --verbose after openstudio_meta and post the results please.

**Comment by nixub-a** [comment]
I used the console in the PAT Developer tool. Was that the correct location?

![image](https://user-images.githubusercontent.com/124007548/228025295-07b81cda-a8c1-4ed1-8b12-9497f4e6b131.png)

**Comment by brianlball** [comment]
run the command in a power shell terminal or cmd window.

**Comment by nixub-a** [comment]
This was my result on PowerShell Admin. 

![image](https://user-images.githubusercontent.com/124007548/228086212-d84d7ece-5068-4adc-945c-be0f5d6f9ce4.png)

**Comment by nixub-a** [comment]
Update: The command seems to work on Git Bash. I got an error message at the end and it refers me to the rail.log file. I included Git Bash response text file and rail log. My issue may be related to permissions being denied. 

![image](https://user-images.githubusercontent.com/124007548/228089782-5c70b39a-2e21-4662-a4b6-6c7fc469d954.png)
[git-bash_response.txt](https://github.com/NREL/OpenStudio-PAT/files/11083756/git-bash_response.txt)
[rails.log](https://github.com/NREL/OpenStudio-PAT/files/11083757/rails.log)

**Comment by nixub-a** [comment]
Here is my mongo.log file as well. 

![image](https://user-images.githubusercontent.com/124007548/228129311-2030c8e8-432f-4d34-9f57-9881f41fa304.png)
[mongo.log](https://github.com/NREL/OpenStudio-PAT/files/11085315/mongo.log)

**Comment by brianlball** [comment]
do you have restricted access on your windows 10 machine?

**Comment by nixub-a** [comment]
I have a weak Windows 11 laptop that can start the server with no issue. In the C:\ParametricAnalysisTool-3.2.1\ of the laptop, it had four more directories that my PC with errors. I added the following folders: 

C:\ParametricAnalysisTool-3.2.1\pat\OpenStudio-server\server\log
C:\ParametricAnalysisTool-3.2.1\pat\OpenStudio-server\server\tmp\cache
C:\ParametricAnalysisTool-3.2.1\pat\OpenStudio-server\server\tmp\pids
C:\ParametricAnalysisTool-3.2.1\pat\OpenStudio-server\server\tmp\sockets

For some reason, I am now able to start a local server and run tests. I do not know why my install did not include the directories. Hopefully, this will help someone under the same predicament.
