### ISSUE TITLE
Example Project for Timeseries Calibration

### ISSUE THREAD

**Issue by kongkun-om** [NREL/OpenStudio-PAT#265]
Hi,
I am interested in performing a Timeseries Calibration as mentioned in the OpenStuio Analysis Spreadsheet Documentation using the PAT Algorithmic Mode approach. Could you please advise me on a working example project I can follow and learn from? Could you please also recommend which analysis algorithms would be appropriate for calibrating chilled water data (e.g., chilled water temperature and kW)?
Thank you very much.

**Comment by brianlball** [comment]
The Timeseries calibration measure can be found [here](https://github.com/NREL/openstudio-calibration-gem/tree/develop/lib/measures/TimeseriesObjectiveFunction)
[here](https://www.nrel.gov/docs/fy19osti/70865.pdf) is a link to a conference paper where we used that measure.
I know thats not super helpful by itself, but I will try and create an example and post it with other examples [here](https://github.com/NREL/docker-openstudio-jupyter).
As far as algorithms go, I would suggest using the screening / sampling ones first to determine bounds for your most sensitive variables, while remove those that are not impactful.  Then use a few different optimization based algorithms and compare the results.

**Comment by kongkun-om** [comment]
Thank you very much for your advice and the provided materials. I will study them and may reach out again if I have further questions.

**Comment by brianlball** [comment]
i've updated the notebooks with a timeseries example https://github.com/NREL/docker-openstudio-jupyter/blob/openstudio/osw_project/TimeseriesModel.ipynb

that repo has an updated Measure that is in this PR https://github.com/NREL/openstudio-calibration-gem/pull/60
