### ISSUE TITLE
PAT v3.7.0 Local Server running EnergyPlus 23.1 

### ISSUE THREAD

**Issue by craig-simmons** [NREL/OpenStudio-PAT#272]
When I run manual analysis using a local server the EnergyPlus runs fail with errors that appear to be due to the server attempting to run them through v23.1 although OS v3.7.0 should run on EnergyPlus v23.2. I've run the exact same workflows and single models through the OS-CLI v3.7.0 with no issues.

One possibility is that the openstudio-extension gem is listed as v0.6.1 instead of the expected v0.7.0, screenshot below.

Attaching the eplusout.err file showing v23.1 on line 1, along with a screenshot of the local server "Admin" tab showing OS versions.

- PAT v3.7.0
- OS-Server (local deployed by PAT) v3.7.0 
- Windows 11

![image](https://github.com/NREL/OpenStudio-PAT/assets/154483654/b79361d6-ff5e-47f7-a67a-fe68e38bc0a0)
![image](https://github.com/NREL/OpenStudio-PAT/assets/154483654/b88bb8a4-aac5-4a17-bcc1-6c24e9832b41)
[eplusout.err.txt](https://github.com/NREL/OpenStudio-PAT/files/13830748/eplusout.err.txt)

**Comment by wenyikuang** [comment]
You are right, the E+ should be updated in PAT:

https://github.com/NREL/OpenStudio-PAT/blob/7c1cfe8af3d9802eeb71192340b2c6ab8a9c61b9/manifest.json#L4-L9

Will update it tomorrow.

**Comment by wenyikuang** [comment]
https://github.com/NREL/OpenStudio-PAT/pull/273 <- could you try it ?

Feel free to ping me on teams.

**Comment by wenyikuang** [comment]
Fixed as upon the PR #273  merged. Release has been updated too.

Along with that, a compatitable issue in intel mac has been fixed.
