### ISSUE TITLE
PAT 3.7.0: "undefined method `getArgumentValues`"

### ISSUE THREAD

**Issue by ainar** [NREL/OpenStudio-PAT#277]
Hi,
As PAT 3.8.0 is unusable (https://github.com/NREL/OpenStudio-PAT/issues/276), I tried PAT 3.70.
However, manual analyses do not run locally when analyzing E+ or OS alternatives with options. It throws the error below.

![image](https://github.com/user-attachments/assets/df8ca4dd-41e2-45f6-9095-785f397ec616)

**Comment by shorowit** [comment]
Presumably the same issue as https://github.com/openstudiocoalition/OpenStudioApplication/issues/722
