### ISSUE TITLE
Path to OpenStudio executable is wrong in the S3 archive for Linux

### ISSUE THREAD

**Issue by ainar** [NREL/OpenStudio-PAT#278]
Hey,
I noticed that the archive for OpenStudio has a different structure, depending on the platform.
- https://openstudio-resources.s3.amazonaws.com/pat-dependencies3/OpenStudio-3.8.0-Windows.tar.gz
For Windows, the path to OpenStudio is _/bin/openstudio.exe_.
- https://openstudio-resources.s3.amazonaws.com/pat-dependencies3/OpenStudio-3.8.0-Linux.tar.gz
For Linux, the path is _/usr/local/openstudio-3.8.0/bin/openstudio_.
https://github.com/NREL/OpenStudio-PAT/blob/52b88566165a45d3f0262ec583fc3840d68a15bc/manifest.json#L63

This path is used there:
https://github.com/NREL/OpenStudio-PAT/blob/52b88566165a45d3f0262ec583fc3840d68a15bc/app/app/main/dependencyManagerService.js#L86
So, the dependency manager cannot find the OpenStudio executable in Linux.

I noticed that this path to the OpenStudio executable is wrong for Linux distributions for OS versions 3.7.0 and 3.8.0

**Comment by wenyikuang** [comment]
```
ddiff <(tar -tzf OpenStudio-3.6.1-Linux.tar | awk -F/ 'NF<3' | sort | uniq) \
     <(tar -tzf OpenStudio-3.9.0-Linux.tar | awk -F/ 'NF<3' | sort | uniq)
2d1
< OpenStudio/CHANGELOG.md
4c3
< OpenStudio/OpenStudio_Release_Notes_3_6_0_20230509.pdf
---
> OpenStudio/OpenStudio_Release_Notes_3_7_0_20231117.pdf
````

Remed this issue in 3.9.0.rc1
