### ISSUE TITLE
Results Icon in PAT's Run Tab Not Populating Correctly

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#31]
_From @ljbrackney on June 27, 2017 17:47_

Observed in build with PAT SHA: 23608c48727821d8ac530e142af60ca78d1bbda6

Ran large project on 24a.  Project ran fine w/ point truncation in PAT.  Even when downloading data points and models, the results icon remains grayed out.  The HTML files in the zip are fine.

![results](https://user-images.githubusercontent.com/2230150/27601955-e95a5746-5b25-11e7-8507-b65ba4c4a1c4.png)

_Copied from original issue: NREL/OpenStudio#2680_

**Comment by kflemin** [comment]
This is (currently) by design.  The zips get downloaded only, not extracted.  The reports are usually downloaded individually, but this doesn't happen on large projects.  Would it be better if we didn't display the report icon at all for large projects?

**Comment by kflemin** [comment]
Removed the report icon in large project so it's less confusing: 6a1b8cb66263b8be5f9d0bcb8c0c6c7a6eb8e081

**Comment by ljbrackney** [comment]
To clarify - you're removing report icons for points that aren't automatically downloaded, or for all points?  I sometimes use reports - even for large projects to make sure things are running ok.

**Comment by kflemin** [comment]
For large projects (> 150 datapoints), we do not download the reports separately.  You could access them from within the data_point.zip file that is downloaded, but they aren't loaded in PAT the way reports are loaded for smaller projects.

**Comment by kflemin** [comment]
Okay, I've reverted this fix so that the report icons still show up on the run tab even for large analyses.  I think this original issue is old and has been fixed along the way.  Closing.
