### ISSUE TITLE
PAT manual analysis fails if no variables are setup

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#43]
_From @DavidGoldwasser on November 8, 2017 17:21_

I setup a PAT project where unique design alternatives were setup by skipping specific measures, with all measure shaving only one design option other than "none". This failed with the following error.

![screen shot 2017-11-08 at 10 10 52 am](https://user-images.githubusercontent.com/4857055/32563399-67370fea-c46e-11e7-9cf9-9160f776d82e.png)

I was able to work around this by just picking any argument in any measure and checking the variable option. I didn't even have to make a second measure option to go with the variable. Seems like we could handle this for the user vs. having failed analysis. This would be that un-common when looking at ECMS that are binary vs. something with a dial to adjust.

Note: the Time Series Objective functions were un-related issue.

_Copied from original issue: NREL/OpenStudio#2840_

**Comment by kflemin** [comment]
_From @ljbrackney on November 8, 2017 17:48_

That is by design.  The server needs at least one variable to function properly without significant development.  It was easiest to trap this on the client side, and you need to check something (anything) as a variable for a project to work correctly.

**Comment by kflemin** [comment]
@DavidGoldwasser,

As Larry mentioned, this is by design. The correct workaround is to select anything as a variable.

PAT projects that 'skip' a measure in at least one alternative would run on the server without setting anything at a variable on the analysis tab.  I can check for skips and allow those to proceed.  Does that work?

**Comment by DavidGoldwasser** [comment]
If we can add check for skipped measure that would be ideal.

**Comment by kflemin** [comment]
Added ability to run analysis without variables if there's at least one skipped measure in a DA:  commit 7c58b6f061ab9ccd41a2bb6a60c1fcc9ecbc7443
