### ISSUE TITLE
Cannot delete Measure Option in PAT

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#48]
_From @jmarrec on June 16, 2017 12:13_

OS 2.1.1, macOS Sierra 10.12

Sometimes when I click on the cross to delete a measure option, it stays there (the cross itself disappears). Upon save and reopen, it's still there, but when I do it again, it disappears. It may be when I click quickly on something else after

![screen shot 2017-06-16 at 2 13 30 pm](https://user-images.githubusercontent.com/5479063/27226181-045183e8-529e-11e7-9877-fdacae653eee.png)

_Copied from original issue: NREL/OpenStudio#2657_

**Comment by kflemin** [comment]
_From @DavidGoldwasser on June 22, 2017 19:21_

@evanweaver have you heard any other reports like this. I can't reproduce this on 2.1.2 macOS 10.11.6

**Comment by kflemin** [comment]
_From @evanweaver on June 22, 2017 19:24_

@DavidGoldwasser I've not experienced this nor heard of it before.

**Comment by kflemin** [comment]
@jmarrec, is this still an issue?

**Comment by jmarrec** [comment]
I'm not sure, I haven't used PAT in ages nor do I still use a macOS machine.
Plus, I think to remember this isn't one the cases where opening a blank project and playing for 2 seconds would reproduce the bug, it was more something that would come up much later.

You can close the issue, and I (or someone else) will reopen if they come across it in 2.4.x.
