### ISSUE TITLE
runner.registerValue with infinity crashes PAT

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-PAT#50]
From https://github.com/NREL/OpenStudio/issues/2670

**Comment by kflemin** [comment]
@macumber Does this really crash PAT?  It sounds like the datapoints fail on the server.  I'm not sure what needs to happen on the PAT side of things...

**Comment by kflemin** [comment]
Tested with measure that has infinity and no PAT crash.

**Comment by macumber** [comment]
I would suggest that @DavidGoldwasser or someone else develop some measures which are purposefully degenerate (e.g. `runner.registerValue('inf', 1.0/0.0, '')` and `runner.registervalue('nan', 0.0/0.0, '')`).  We can run these as part of our test suites for the server and PAT.

**Comment by kflemin** [comment]
sounds good to me!
