### ISSUE TITLE
PAT Measure Manager Not Finding New Content in MyMeasures

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#55]
_From @ljbrackney on August 28, 2017 15:57_

Added a Measure to MyMeasures.

[RunPeriod.zip](https://github.com/NREL/OpenStudio/files/1257399/RunPeriod.zip)

This didn't show up in PAT's Measure Manager but DID show up in the App.  I manually edited the Measure's XML to delete a word from the description and restarted PAT.  The Measure now shows up and can be added to the project.

_Copied from original issue: NREL/OpenStudio#2759_

**Comment by kflemin** [comment]
_From @macumber on January 12, 2018 23:4_

@kflemin should this be moved to PAT repo?

**Comment by kflemin** [comment]
Could not reproduce.  If it's ok with you, I'd like to close this issue, but we can re-open if you run into a similar issue again.  I have also added potential measure manager 'errors' related to specific measures in RED in the developer console, so they are easier to spot.  Also check there if this happens again.

**Comment by ljbrackney** [comment]
Ok to close.
