### ISSUE TITLE
Enable user entered string for choice list from model objects

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#59]
I believe this was in design but just not implemented. Currently for a measure you can choose which seed model is used to calculate choice argument options, but since we allow different seeds for different design alternatives this doesn't allows give users the choice they need for a specific measure option.

**Comment by kflemin** [comment]
@DavidGoldwasser should this be allowed for any choice argument?  Or for model-dependent ones only?

**Comment by DavidGoldwasser** [comment]
@kflemin it is only necessary for model dependent.

**Comment by kflemin** [comment]
this should be fixed as of 5696d962e046583b38537da98de9d35dc865cfc4

**Comment by DavidGoldwasser** [comment]
Working now that I fixed my PAT build :)
