### ISSUE TITLE
Run Tab is broken w/ latest commits

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio-PAT#61]
![runtab](https://user-images.githubusercontent.com/2230150/35653092-4fb4b4d4-069b-11e8-8a69-e2334ee67ad1.png)

This is what the run tab currently looks like with two of my projects that were working in 2.4.0.

**Comment by ljbrackney** [comment]
Debug log after PAT startup:

showInfoMessages =  true
vendor-ad64e72158.js:5 showErrorMessages =  true
vendor-ad64e72158.js:5 Number of cores:  4
vendor-ad64e72158.js:5 Number of workers set to:  3
vendor-ad64e72158.js:5 Selected Server URL set to:  http://localhost:8080
vendor-ad64e72158.js:5 get openstudio version command:  "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/bin/openstudio" openstudio_version
vendor-ad64e72158.js:5 Measure Manager port:  3100
vendor-ad64e72158.js:5 Start Measure Manager Server:  /Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/bin/openstudio  measure -s  3100
events.js:163 Uncaught Error: spawn /Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/bin/openstudio ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
vendor-ad64e72158.js:5 exec error:  Error: Command failed: "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/bin/openstudio" openstudio_version
/bin/sh: /Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/bin/openstudio: No such file or directory

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
(anonymous) @ vendor-ad64e72158.js:5
vendor-ad64e72158.js:5 OPENSTUDIO SERVER AMIS:  Array(24)
vendor-ad64e72158.js:5 OS Server Versions:  Array(24)
vendor-ad64e72158.js:5 SetProjectService::stop server: server stopped
vendor-ad64e72158.js:5 response:  Server already stopped
vendor-ad64e72158.js:5 BCLService::checkForUpdates vm.Project.getMeasuresDir() returned nil
(anonymous) @ vendor-ad64e72158.js:5
vendor-ad64e72158.js:5 Selected Server URL set to:  http://localhost:8080
vendor-ad64e72158.js:5 START SERVER...SERVER TYPE:  local
vendor-ad64e72158.js:5 SERVER STATUS:  stopped
vendor-ad64e72158.js:5 stop server command:  "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/ruby/bin/ruby" "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta" stop_local "/Users/lbrackne/Documents/OpenStudio/K12_HVAC_Study"
app-04dffcbd72.js:6 THE PROCESS TERMINATED
app-04dffcbd72.js:6 exec error:  Error: Command failed: "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/ruby/bin/ruby" "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta" stop_local "/Users/lbrackne/Documents/OpenStudio/K12_HVAC_Study"


    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
vendor-ad64e72158.js:5 start server command:  "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/ruby/bin/ruby" "/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta" start_local --worker-number=3 --energyplus-exe-path="/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/EnergyPlus/energyplus" --ruby-lib-path="/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/Ruby" --mongo-dir="/Users/lbrackne/GitHub/OpenStudio/build/pat/OpenStudio-PAT/tmp/ParametricAnalysisTool.app/Contents/Resources/mongo/bin" --debug "/Users/lbrackne/Documents/OpenStudio/K12_HVAC_Study"
app-04dffcbd72.js:6 Child pid: 68593

**Comment by kflemin** [comment]
I don't see anything about the run tab in the debug log above, but it is complaining that it can't find OpenStudio...can you see it in ParametricAnalysisTool.app/Contents/Resources/?

As for the run tab, were there other errors after the ones above?

**Comment by ljbrackney** [comment]
Resolved
