### ISSUE TITLE
PAT project reports fail sometimes and work other times when switching away form and back to a report

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#62]
This does happen more on larger projects, than smaller ones, but not always.

In the example below with build of PAT vs. installer, the report works when I first go to reporting tab

<img width="1680" alt="screen shot 2018-02-04 at 11 06 31 am" src="https://user-images.githubusercontent.com/4857055/35819238-5071e514-0a5f-11e8-9f35-228c349287d3.png">

And then breaks if I leave to go to other reports and come back. Sometimes I just have to try 4 or 5 times and it works, but this 2400 datapoint project is stubborn. I seem to have to leave reports tab and then go back to reports tab, and I can only view the report that comes up by default.

<img width="1680" alt="screen shot 2018-02-04 at 11 05 25 am" src="https://user-images.githubusercontent.com/4857055/35819289-774374d2-0a5f-11e8-9c36-e053b45728d2.png">

**Comment by kflemin** [comment]
should be fixed on algorithmic_reports branch

**Comment by DavidGoldwasser** [comment]
Thanks!
