### ISSUE TITLE
Can't get datapoint from X-Y plot

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio-PAT#64]
I'm not 100% sure on the cause of it, but the X-Y scatter plots of Office_Study (currently on nrel24b, but may not be when this bug is resolved) don't allow for a datapoint to be viewed when a datapoint is clicked on. The console throws an error stating "d.x.toFixed is not a function". When a datapoint is clicked on it shows the image below.

![image](https://user-images.githubusercontent.com/15233892/36567035-70254046-17e2-11e8-982c-adbd1912828b.png)

**Comment by kflemin** [comment]
this was fixed by @brianlball on the OpenStudio-server side.
