### ISSUE TITLE
Deleting first measure option of a measure instance in manual analysis creates issues.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#65]
I have seen this before, but I have a new project I made in 2.4.2 that exhibits this. After deleting what was the first measure option I can no longer set a project default argument value for the measure instance for the rest of the measure options. The work around is to set it to a variable.

What is confusing for the user is that it looks like it is accepting the value when you set it, but it isn't used for the analysis.

Here is an example project
https://github.com/NREL/FRP_Models/tree/shared_csv/PAT%20Projects/PAT_FRP_1803_no_rtu

**Comment by DavidGoldwasser** [comment]
Here is a screenshot of GUI and simulation results. The argument changes  HVAC availability.  

![screen shot 2018-03-02 at 9 11 15 am](https://user-images.githubusercontent.com/4857055/36908982-12a5f1ae-1dfa-11e8-9a89-0929654ed517.png)
![screen shot 2018-03-02 at 9 11 00 am](https://user-images.githubusercontent.com/4857055/36908994-1b592d48-1dfa-11e8-83cd-6ad525e60d7f.png)

And this is after changing it to an argument, but with the same value.

![screen shot 2018-03-02 at 9 11 23 am](https://user-images.githubusercontent.com/4857055/36909022-2953faea-1dfa-11e8-9325-7eebc65d7745.png)

![screen shot 2018-03-02 at 9 12 30 am](https://user-images.githubusercontent.com/4857055/36909030-2d58bed2-1dfa-11e8-8733-e885ef4fee7c.png)

**Comment by kflemin** [comment]
@DavidGoldwasser can you send me this project? I don't have access to the repo.  thanks!

**Comment by DavidGoldwasser** [comment]
@kflemin, sorry about that, I'll send project in few minutes

**Comment by DavidGoldwasser** [comment]
<img width="1680" alt="screen shot 2018-03-12 at 10 47 23 pm" src="https://user-images.githubusercontent.com/4857055/37323162-84706ae4-2647-11e8-91cf-90e2eb1c4669.png">

OSW file on right for reference.

**Comment by kflemin** [comment]
Fixed in b4cb7c567fb442abca097dd624a6b236b2e1d2fc.
