### ISSUE TITLE
Custom Measure Instance names on first tab don't make it to Design Alternatives tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#68]
<img width="841" alt="screen shot 2018-03-06 at 7 58 03 am" src="https://user-images.githubusercontent.com/4857055/37039349-7cded316-2114-11e8-80c4-d252eed3120c.png">

<img width="842" alt="screen shot 2018-03-06 at 7 58 26 am" src="https://user-images.githubusercontent.com/4857055/37039348-7ca44df4-2114-11e8-9aa5-70639695ddc3.png">

I confirmed they don't refresh after a save, quit and re-load. Not critical for 2.5.0

**Comment by DavidGoldwasser** [comment]
Also don't make it to server

![screen shot 2018-03-08 at 10 28 29 am](https://user-images.githubusercontent.com/4857055/37166153-8ba15696-22bb-11e8-951f-7d44808bad9b.png)

**Comment by kflemin** [comment]
Fixed DA tab in 2cd90bfd2dc407833eb5b3d99cf96e33ecf9c14f.  The server shows measure names (not display names).  This would require a change on the server...
