### ISSUE TITLE
Feature request: An option to enable or disable the automatic start of the local server

### ISSUE THREAD

**Issue by padmassun** [NREL/OpenStudio-PAT#83]
Requesting an option to enable or disable the automatic start of the local server within the `Window` > `Server tools` 

If PAT is _just_ used for running simulations using AWS server, the local server is not needed. The local server takes too much resources and it takes a while to stop. So it would be nice to have an option, where the automatic start of the local server can be prevented.

Thank you.

**Comment by shorowit** [comment]
There was similar discussion for this feature here: https://github.com/NREL/OpenStudio-PAT/issues/34

**Comment by padmassun** [comment]
For windows I use the following workaround to forcefully stop the server.

I run the following script (saved as a .bat file) after I press the stop server button in PAT. This will kill all ruby processess and mongo databases currently running on the windows computer.
```
taskkill /F /IM ruby.exe
taskkill /F /IM mongod.exe
```

_**WARNING: Please do not run this script if you have any other processes running their own ruby or mongo databases.**_

**Comment by brianlball** [comment]
PAT local server is now off by default https://github.com/NREL/OpenStudio-PAT/pull/139
