### ISSUE TITLE
Additional Analysis Files path doesn't make it into OSW's

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-PAT#87]
When I add a directory in PAT it makes it into the analysis.zip file under "lib". That is what I expect, but what isn't happening is the path doesn't make it into the analysis.json file, and as a result doesn't make it into the osw files for the individual datapoints for "file_paths"

As a result I can't use `runner.workflow.findFile(external_file_name)` from measures to find the external files. 

@macumber was the intent of the "file_paths" in the OSW file so PAT could add additional paths beyond "seeds", "weather". If we can support custom paths, could we at least use "lib" I think I may be able to get files to "lib" if I leave "Directory Name to Unpack on Server" to a blank string?

```
file_paths: [
"../weather",
"../seeds",
"../seed"
],
```

**Comment by DavidGoldwasser** [comment]
Screenshot for reference of view in PAT 

<img width="1134" alt="screen shot 2018-07-09 at 9 55 07 pm" src="https://user-images.githubusercontent.com/4857055/42489256-3f281314-83c7-11e8-8398-265f729fd6d9.png">

**Comment by macumber** [comment]
Yeah the intent was to be able to add paths to find files in.  Not sure about user defined folders names uploaded to server, one issue is how to specify the order to search those folders for.  Maybe unpack all the files into a particular directory with a known name?  Or just recursively add all user uploaded folder names in order?

**Comment by DavidGoldwasser** [comment]
I just wanted to add some details to screenshot example above, and layout out the use case a bit. The use case would be for a model or energy plus measure to pull in an external model or other file type like floorplan.json, gbxml file, or in some cases csv file. Another use case would be for a reporting measure to pull in a csv file of time series metered data.

1. In the example above the directory in the zip file would be `lib/name_on_server`
2. I don't believe there is a way to store this in the analysis JSON (OSA) currently. The closest to this is the `seed` and `weather_file` which each store. path to a single file within a directory.
3. The OpenStudio workflow (OSW) already has an array of paths (in fact a few different array of paths) that OpenStudio Server writes to Below is an example OSW from the server.

```
"file_paths": [
"/Users/dgoldwas/Documents/GitHub/NREL/Advanced-Building-Construction/PAT-Projects/Build Unit Model/temp_data/analysis_ed15422e-c3fa-4d0a-86a8-553884ee635a/data_point_1df3dab0-4f8a-4402-a14c-40acef182367/generated_files",
"../weather",
"../seeds",
"../seed",
"./files",
"./weather",
"../../files",
"../../weather",
"./"
],
"hash": "DF60BC30",
"measure_paths": [
"../measures"
],
"name": "Single Run Autogenerated",
"osa_id": "ed15422e-c3fa-4d0a-86a8-553884ee635a",
"osd_id": "1df3dab0-4f8a-4402-a14c-40acef182367",
"run_directory": "./run",
"seed_file": "Rajat_1.osm",
```

I'm not proposing a change to measure_paths right now, PAT has all measure in one directory and that is mirrored on the server. In the future PAT can support measure gems and pull in measure from those gems on the server or when building the zip. But that is a different topic.
** However if we are extending OSA to store file paths, maybe at same time could store measure paths as well and write to OSW in same fashion as files. This could be slick solution if as worker initialization script we install measure gems in the repo. We could simplify what is uploaded in zip file to measures unique to this specific project.

What I am proposing is adding something to the OSA from what is already stored in PAT.json to add the following to `file_paths`. If the user entered multiple directories then multiple paths would be added.
```
"./lib/name_on_server"
```
I had a thought that maybe only `./lib` would be necessary, but I'm pretty sure `findFile` in runner doesn't look in nested directories, but I have not tested to confirm that. If it does look in nested directories, then maybe we can add hard coded `lib` and nothing else. I'll try to test.

**Comment by DavidGoldwasser** [comment]
One main limitation of `findFile` that I should point out is that it stops the first file it finds of the requested name. I don't know for sure the order it looks through the directories, but the point is when using this all of the names should be unique, so you should not make a bunch of unique directory names with non-unique file names like `in.osm` in it. It won't through an error but may give unexpected results. This issue isn't unique to files, it is also true when multiple measure paths are included and different versions of the measure are found in different measure directories.

**Comment by DavidGoldwasser** [comment]
Some of the files I showed above may have been added by OpenStudio Workflow gem, not OpenStudio server. When passed in an OSW that looks like this
```
  "file_paths": [
    "../../seeds",
    "../../weather"
  ],
```

The out.osw looks like this. I assume those are added ahead of the run and available to measures. That could inadvertently cause problems.  
```
   [
      "/Users/dgoldwas/Documents/GitHub/NREL/Advanced-Building-Construction/workflows/single_unit_test/generated_files",
      "../../seeds",
      "../../weather",
      "./files",
      "./weather",
      "../../files",
      "../../weather",
      "./"
   ],
```

**Comment by DavidGoldwasser** [comment]
Ok, so the test about nested search with `findFile` wasn't all bad. I did in fact confirm that it will not search nested directories, but I also found that I can provide a partial path instead of a file name. Here are two scenarios

Full path included in OSW
```
  "file_paths": [
    "../../seeds",
    "../../weather",
    "../../lib/name_on_server"
  ],
```

In this scenario I can use an argument of just `ofice_plan.json`

In the second scenario only the path to `lib` is defined
```
  "file_paths": [
    "../../seeds",
    "../../weather",
    "../../lib"
  ],
```
In this case my argument needs to include part of the path, so `name_on_server/office_plan.json` would find the file.

The advantage of scenario 2 is that this could probably be added by OpenStudio Workflow gem in the same way that "files" and other directories are already added, and then maybe no changes are needed to OpenStudio Server.
Another possible advantage is that users could have duplicate file names under sub-directories of `lib` and grab that right one.

Disadvantage os second scenario is that it takes away the simplicity just a file name from user arguments, and requires person using pat to be aware of the additional files structure. Additionally, if file structure is changed, measure arguments need to be updated, which would not e the case in the first scenario.

**Comment by DavidGoldwasser** [comment]
PAT could change to replace `lib` with `files` and what is needed would already be in the expanded OSW but I expect that would create lots of headaches. It would also be odd to duplicate content to both `lib` and `files`

Having OpenStudio server include `../../lib` and potentially sub-directories of saved in OSA seems like best approach.

In considering why `files` is included I think that goes back to how OS App stores weather files, and possibly floorplan json?

If we do go into OpenStudio Workflow gem I also wonder if it makes sense to clean up some fo the redundant forms of `files` and `weather`, but could create un-necessary headaches if anyone has OSW's setup expecting those to be automatically added, of course has easy workaround of them updating their OSW's to explicitly list the paths.

**Comment by DavidGoldwasser** [comment]
Development Plan for OpenStudio 3.1
1. Will update OpenStudio Analysis gem to add `../../lib` to OSW's then measures could use `short_path/filename.ext` where `short_pat` is the name they entered in pat for "Directory Name to Unpack to on Server"

There is an open issue for supporting additional files in manual mode (it already works if you go to algorithmic to setup and then go back to manual), but isn't evident to most people using manual.This would avoid the need to have measures access files on their computer external to the project. This issue doesn't have to be in 3.1. it can be in later release.
https://github.com/NREL/OpenStudio-PAT/issues/78

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio-analysis-gem/pull/44

**Comment by brianlball** [comment]
@DavidGoldwasser this is fixed by https://github.com/NREL/OpenStudio-analysis-gem/pull/44?
